version: "3"
services:
  db:
    image: "iitkavinash/rachvik-id:latest"
    container_name: "rachvik_id"
    environment:
      SERVER_PORT: "5556"
      SPRING_PROFILE: "prod"
    ports:
      - "5556:5556"