spring:
  datasource:
    url: jdbc:postgresql://rachvik-master.c5cugiycotd6.us-east-1.rds.amazonaws.com:5432/rachvik
    username: postgres
    password: my_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080


