spring:
  cassandra:
    port: 9042
    contact-points: cassandra_server
    keyspace-name: rummy
    schema-action: create_if_not_exists
  data:
    mongodb:
      username: avinash
      password: avinash
      host: localhost
      port: 27017
      database: rummy
      authentication-database: admin
server:
  port: 8084
grpc:
  server:
    port: 5558
